export const SELECT_JOB = 'SELECT_JOB';

export const SELECT_JOB_SUCCESS = 'SELECT_JOB_SUCCESS';
export const SELECT_JOB_FAILED = 'SELECT_JOB_FAILED';

export const LOGIN_USER_REQUEST ='LOGIN_USER_REQUEST';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const BOOKMARK_JOB = 'BOOKMARK_JOB';
export const APPLY_JOB = 'APPLY_JOB';
export const ADD_BOOKMARK ='ADD_BOOKMARK';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const ADD_LETTER = 'ADD_LETTER';
export const RECEIVE_JOBS = 'RECEIVE_JOBS';
export const RECEIVE_BOOKMARKS = 'RECEIVE_BOOKMARKS';
export const RECEIVE_APPLICATIONS = 'RECEIVE_APPLICATIONS';
export const RECEIVE_LETTERS = 'RECEIVE_LETTERS';

