export const SELECT_JOB = 'SELECT_JOB';
export const SELECT_JOB_SUCCESS = 'SELECT_JOB_SUCCESS';
export const SELECT_JOB_FAILED = 'SELECT_JOB_FAILED';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const BOOKMARK_JOB = 'BOOKMARK_JOB';
export const BOOKMARK_JOB_SUCCESS = 'BOOKMARK_JOB_SUCCESS';
export const BOOKMARK_JOB_FAILED = 'BOOKMARK_JOB_FAILED';

export const APPLY_JOB = 'APPLY_JOB';
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_FAILED = 'APPLY_JOB_FAILED';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK_FAILED = 'ADD_BOOKMARK_FAILED';

export const ADD_APPLICATION = 'ADD_APPLICATION';
export const ADD_APPLICATION_SUCCESS = 'ADD_APPLICATION_SUCCESS';
export const ADD_APPLICATION_FAILED = 'ADD_APPLICATION_FAILED';

export const ADD_LETTER = 'ADD_LETTER';
export const ADD_LETTER_SUCCESS = 'ADD_LETTER_SUCCESS';
export const ADD_LETTER_FAILED = 'ADD_LETTER_FAILED';

/// TODO
export const FETCH_JOBS_FROM_LOCAL = 'FETCH_JOBS_LOCAL';
export const FETCH_JOBS_FROM_LOCAL_SUCCESS = 'FETCH_JOBS_FROM_LOCAL_SUCCESS';
export const FETCH_JOBS_FROM_LOCAL_FAILED = 'FETCH_JOBS_FROM_LOCAL_FAILED';

export const RECEIVE_JOBS = 'RECEIVE_JOBS';
export const RECEIVE_JOBS_SUCCESS = 'RECEIVE_JOBS_SUCCESS';
export const RECEIVE_JOBS_FAILED = 'RECEIVE_JOBS_FAILED';

export const RECEIVE_BOOKMARKS = 'RECEIVE_BOOKMARKS';
export const RECEIVE_BOOKMARKS_SUCCESS = 'RECEIVE_BOOKMARKS_SUCCESS';
export const RECEIVE_BOOKMARKS_FAILED = 'RECEIVE_BOOKMARKS_FAILED';

export const RECEIVE_APPLICATIONS = 'RECEIVE_APPLICATIONS';
export const RECEIVE_APPLICATIONS_SUCCESS = 'RECEIVE_APPLICATIONS_SUCCESS';
export const RECEIVE_APPLICATIONS_FAILED = 'RECEIVE_APPLICATIONS_FAILED';

export const RECEIVE_LETTERS = 'RECEIVE_LETTERS';
export const RECEIVE_LETTERS_SUCCESS = 'RECEIVE_LETTERS_SUCCESS';
export const RECEIVE_LETTERS_FAILED = 'RECEIVE_LETTERS_FAILED';

export const OPEN_DISCUSS_MODAL = 'OPEN_DISCUSS_MODAL';
export const CLOSE_DISCUSS_MODAL = 'CLOSE_DISCUSS_MODAL';

export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const RECEIVE_PROFILE_SUCCESS = 'RECEIVE_PROFILE_SUCCESS';
export const RECEIVE_PROFILE_FAILED = 'RECEIVE_PROFILE_FAILED';

export const RECEIVE_TAGS = 'RECEIVE_TAGS';
export const RECEIVE_TAGS_SUCCESS = 'RECEIVE_TAGS_SUCCESS';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

// Maybe use ?
export const RECEIVE_COMPANY = 'RECEIVE_COMPANY';
export const RECEIVE_COMPANY_SUCCESS = 'RECEIVE_COMPANY_SUCCESS';
export const RECEIVE_COMPANY_FAILED = 'RECEIVE_COMPANY_FAILED';

export const RECEIVE_JOB = 'RECEIVE_JOB';
export const RECEIVE_JOB_SUCCESS = 'RECEIVE_JOB_SUCCESS';
export const RECEIVE_JOB_FAILED = 'RECEIVE_JOB_FAILED';
// End of maybe use ? 

export const RECEIVE_JOB_DESC = 'RECEIVE_JOB_DESC';
export const RECEIVE_JOB_DESC_SUCCESS = 'RECEIVE_JOB_DESC_SUCCESS';
export const RECEIVE_JOB_DESC_FAILED = 'RECEIVE_JOB__DESC_FAILED';

export const TOGGLE_APPLY_FORM_SUCCESS = 'TOGGLE_APPLY_FORM_SUCCESS';
export const TOGGLE_TEMPLATE_FORM_SUCCESS = 'TOGGLE_TEMPLATE_FORM_SUCCESS';
